### ISSUE TITLE
Cannot compile for x86_64 by following instructions.

### ISSUE THREAD

**Issue by ArvReh** [NathanMcMillan54/novusk#15]
```
src/novusk # make all ARCH=x86 TARGET_ARCH=x86_64 DEVICE=default
make[1]: Entering directory 'src/novusk/arch/x86'
make[1]: *** No rule to make target 'clean'.  Stop.
make[1]: Leaving directory 'src/novusk/arch/x86'
make: *** [Makefile:18: clean] Error 2
src/novusk #
 ```
While I could probably fix this myself with 15 minutes of tinkering, the specified instruction should work.

**Comment by NathanMcMillan54** [comment]
Which version are you trying to compile?

**Comment by NathanMcMillan54** [comment]
I'm assuming this could be because of documentation between v2 and v2.1.3, just go to ``arch/x86/`` and try this:

```command line
cargo build --features default_machine --target targets/x86_64-novusk.json```

If you want to use Make to compile the kernel:

The error is probably caused from not being able to find a "clean" function, try removing ``clean`` from the ``all`` function.

**Comment by ArvReh** [comment]
I'm using master, and there is no Makefile in `arch/x86/`. There is not `default_machine` feature for the crate `x86`. If I remove that it then complains that it can't find the crate core; I suspect this is because you have not specified to `core`.

**Comment by NathanMcMillan54** [comment]
If you were using Novusk v2 - Novusk v2.1.3 the comment above is what you should do, if you're compiling for the master branch there shouldn't be any problems with compiling. Try this:

```command line
make all ARCH=x86_64 ARCH_FAM=x86 BOOT_METHOD=uefi DEVICE=default_machine
```

The master branch is being rewritten and has no documentation.

**Comment by NathanMcMillan54** [comment]
[9609db8](https://github.com/NathanMcMillan54/novusk/commit/9609db8ad1466582af7c3fed0f310b8c833c5170) in [Documentation/setup](https://github.com/NathanMcMillan54/novusk/tree/master/Documentation/setup).

**Comment by NathanMcMillan54** [comment]
That is how you compile Novusk on the master branch ^^^
