### ISSUE TITLE
Discord link expired

### ISSUE THREAD

**Issue by actuallyexeon** [NathanMcMillan54/novusk#18]
Please make the link last for infinity
![image](https://user-images.githubusercontent.com/46092609/125179245-84994e80-e1b2-11eb-8863-1b6047f2dec0.png)
![image](https://user-images.githubusercontent.com/46092609/125179250-92e76a80-e1b2-11eb-8bfb-20c55b07e111.png)

**Comment by NathanMcMillan54** [comment]
Ya sorry, I was told by some people that the discord link doesn't work but I haven't been told why. Thank you for letting me know!

**Comment by NathanMcMillan54** [comment]
[3c7c3b8](https://github.com/NathanMcMillan54/novusk/commit/3c7c3b81262080e1bd4e94c8bce9d2de7d394acb) - Updated Discord join link in README.md
